### ISSUE TITLE
[Feature] Indentation of algorithmic commands

### ISSUE THREAD

**Issue by vepain** [WGUNDERWOOD/tex-fmt#107]
## Aim

Being able to configure command blocks (where the beginning and end differ) for which the sub content is idented.

## Application

For pseudocode environements

## Example

With `\If` and `\EndIf` command block:

```tex
\begin{algorithmic}[1]
  \If{ ... }
    \State{} ...
  \EndIf{}
\end{algorithmic}
```

## Going further

Some of these command accept middle command, e.g. `\If` `ElseIf`  `Else` `EndIf`.

```tex
\begin{algorithmic}[1]
  \If{ ... }
    \State{} ...
  \ElseIf{ ... } % same indentation as the \If
    \State{} ...
  \Else{}
    \State{} ...
  \EndIf{}
\end{algorithmic}
```

## User configuration ideas

At the opposite of `lists` or `verbatim` configurations, it is necessary to define a block with a `begin_cmd` (a string), `end_cmd` (a string) and `middle_cmd` (a list of strings)

```toml
[[blocks]]

    [[blocks.IfElseIfElse]]

        begin = "If"
        middle = ["ElseIf", "Else"]
        end = "EndIf"
```
