### ISSUE TITLE
Incorrect merging of conflicting argument values

### ISSUE THREAD

**Issue by cdesaintguilhem** [WGUNDERWOOD/tex-fmt#73]
With the following config file at `/Users/<username>/Library/Application\ Support/tex-fmt/tex-fmt.toml`:
```toml
# Cyprien's tex-fmt.toml
check = false
print = false
wrap = true
wraplen = 120
tabsize = 2
tabchar = "space"
stdin = false
verbosity = "info"
```
running `tex-fit --args` from `~/` yields the following output:
```shell
tex-fmt
  check:       false
  print:       false
  wrap:        true
  wraplen:     80
  wrapmin:     70
  tabsize:     2
  tabchar:     space
  stdin:       false
  config:      /Users/<username>/Library/Application Support/tex-fmt/tex-fmt.toml
  verbosity:   warn
```

This shows that the configuration file is correctly picked up from the default macOS location, but the merge resolution of `120` with `80` yields the default value of `80` rather than the expected `120`. Similarly, the merge resolution of `info` with `warn` yields the default of `warn` rather than the expected `info`.
