### ISSUE TITLE
v0.5.3 nonexistent

### ISSUE THREAD

**Issue by jeroenoverdevest93** [WGUNDERWOOD/tex-fmt#98]
By adding the following config to ``.pre-commit-config.yaml` using
```
repos:
  - repo: https://github.com/WGUNDERWOOD/tex-fmt
    rev: v0.5.3
    hooks:
      - id: tex-fmt
```

we cannot install `.git\hooks\pre-commit` and get the following error when running `pre-commit`:
```
E:\home\tex\project>pre-commit 
An error has occurred: InvalidManifestError: 
=====> C:\Users\x\.cache\pre-commit\repoc9rrd54e\.pre-commit-hooks.yaml is not a file
Check the log at C:\Users\x\.cache\pre-commit\pre-commit.log
```

I would suggest tagging the current main branch to `v0.5.3`.
